export { StaticAlt, FantasyAlt } from './Alt'
export { StaticAlternative, FantasyAlternative } from './Alternative'
export { StaticApplicative, FantasyApplicative } from './Applicative'
export { StaticApply, FantasyApply } from './Apply'
export { StaticBifunctor, FantasyBifunctor } from './Bifunctor'
export { StaticChain, FantasyChain } from './Chain'
export { StaticChainRec } from './ChainRec'
export { StaticComonad, FantasyComonad } from './Comonad'
export { StaticContravariant, FantasyContravariant } from './Contravariant'
export { StaticCopointed, FantasyCopointed } from './Copointed'
export { StaticExtend, FantasyExtend } from './Extend'
export { StaticFoldable, FantasyFoldable } from './Foldable'
export { StaticFunctor, FantasyFunctor } from './Functor'
export { HKT } from './HKT'
export { StaticMonad, FantasyMonad } from './Monad'
export { StaticMonoid } from './Monoid'
export { StaticOrd } from './Ord'
export { Ordering } from './Ordering'
export { StaticPlus, FantasyPlus } from './Plus'
export { StaticPointedFunctor } from './PointedFunctor'
export { StaticSemigroup } from './Semigroup'
export { StaticSetoid } from './Setoid'
export { StaticTraversable, FantasyTraversable } from './Traversable'
export { StaticUnfoldable } from './Unfoldable'
